# Site settings
baseURL: 'https://yuri-busin-site.pages.dev/'
title: 'Dr. Yuri Busin'
defaultContentLanguage: pt-br

# Build settings
enableRobotsTXT: yes
disableHugoGeneratorInject: yes
disableKinds: ['taxonomy', 'taxonomyTerm']
paginate: 6
