# Site settings
baseURL: '/'
title: 'Dr. Yuri Busin'
defaultContentLanguage: pt-br

# Build settings
enableRobotsTXT: yes
disableHugoGeneratorInject: yes
disableKinds: ['taxonomy', 'taxonomyTerm']
paginate: 6
