# Site settings
baseURL: 'https://yuri-busin-site.pages.dev/'
title: 'Dr. Yuri Busin'
defaultContentLanguage: pt-br

# Build settings
enableRobotsTXT: yes
disableHugoGeneratorInject: yes
paginate: 6
removePathAccents: true

taxonomies:
  category: category

permalinks:
  category: '/blog/categoria/:slug/'

params:
  whatsApp: 'https://wa.me/5511999646940'
  facebook: 'https://www.facebook.com/yuribusinpsicologo/'
  instagram: 'https://www.instagram.com/dryuribusin/'
  youtube: 'https://www.youtube.com/channel/UCcmQYl3OkMp3HmhRQs3mPHA'
  email: 'contato@yuribusin.com.br'
  phone: '551141168926'
  googleMaps: 'https://goo.gl/maps/ChkZLjVBCgUBhVd86?coh=178572&entry=tt'

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 80
