# Site settings
baseURL: https://yuri-busin-site.pages.dev/
title: 'Dr. Yuri Busin'
defaultContentLanguage: pt-br

# Build settings
paginate: 6
enableRobotsTXT: yes
removePathAccents: true
disableHugoGeneratorInject: yes
paginate: 6
removePathAccents: true

# Production environment settings
environment:
  HUGO_VERSION: "0.115.0"
  NODE_VERSION: "18.16.1"

# Taxonomies settings
taxonomies:
  category: category

# Permalinks settings
permalinks:
  category: /categoria/:slug/

# Custom params
params:
  whatsApp: 'https://wa.me/5511999646940'
  email:
    address: contato@yuribusin.com.br
    link: mailto:contato@yuribusin.com.br
  phone:
    number: (11) 4116-8926
    link: 'tel:+551141168926'
  address:
    formatted: R. Voluntários da Pátria, 2468 - Cj - 214 <br> Santana, São Paulo - SP, 02401-000
    link: https://goo.gl/maps/ChkZLjVBCgUBhVd86?coh=178572&entry=tt
  social:
    tikTok: https://www.tiktok.com/@dryuribusin
    facebook: https://www.facebook.com/yuribusinpsicologo/
    instagram: https://www.instagram.com/dryuribusin/
    youtube: https://www.youtube.com/channel/UCcmQYl3OkMp3HmhRQs3mPHAs

# Image processing settings
imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: photo
  quality: 80
